model:
  method : classification # classification or regression
  model_type : sli_rec
  layer_sizes : [100, 64]  # layers' size of DNN. In this example, DNN has two layers, and each layer has 100 hidden nodes.
  att_fcn_layer_sizes : [80, 40]
  activation : [relu, relu] # activation function for DNN
  user_dropout: True
  dropout : [0.3, 0.3]  #drop out values for DNN layer
  item_embedding_dim : 32 # the embedding dimension of items
  cate_embedding_dim : 8  # the embedding dimension of categories
  user_embedding_dim : 16 # the embedding dimension of users

train:
  loss : softmax    # pointwise: log_loss, cross_entropy_loss, square_loss  pairwise: softmax
  batch_size : 400  # batch size, should be constrained as an integer multiple of the number of (1 + train_num_ngs) when need_sample is True
  enable_BN : True  # whether to use batch normalization in hidden layers
  max_seq_length : 50 # the maximum number of records in the history sequence
  hidden_size : 40 # the shape of hidden size used in RNN
  attention_size : 40 # the shape of attention size
